workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.example.myapp" # 替换为你的应用包名
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build the project
        script: npm run build
      - name: Copy Capacitor files
        script: npx cap sync ios
    artifacts:
      - build/ios/ipa/**/*.ipa
    publishing:
      app_store_connect:
        credentials:
          api_key: $APP_STORE_API_KEY
          key_id: $KEY_ID
          issuer_id: $ISSUER_ID
  android-build:
    name: Android Build
    environment:
      android: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build the project
        script: npm run build
      - name: Copy Capacitor files
        script: npx cap sync android
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_CREDENTIALS
